### ISSUE TITLE
Rails?

### ISSUE THREAD

**Issue by anitagraham** [digital-fabric/rubyoshka#12]
Is there a Rails template handler for papercraft?

thanks, Anita

**Comment by noteflakes** [comment]
HI, no, for the moment there isn't one. I'll try and find a moment to work on it, but personally this is not a priority. I'm always open to contributions :-).

**Comment by noteflakes** [comment]
As of version 0.29, Papercraft has Tilt integration, so I'm considering this issue as fixed.
