### ISSUE TITLE
Template composition doesn't render inner templates.

### ISSUE THREAD

**Issue by dhnaranjo** [digital-fabric/rubyoshka#13]
Hello! So. I was trying to build some components for which to compose some forms and, without fail, when I placed a template in another template it would, instead of rendering the tree of components, render the outermost component and then wrap the props of the first level down components in the name of the component.

This is true for the example in the README at https://github.com/digital-fabric/papercraft#template-composition, which outputs the following (ran through a pretty printer)

```
<!DOCTYPE html>
<html>
   <head>
      <Title>Hello from composed templates</Title>
   </head>
   <body>
      <ItemList>[{:id=&gt;1, :text=&gt;&quot;foo&quot;, :checked=&gt;false}, {:id=&gt;2, :text=&gt;&quot;bar&quot;, :checked=&gt;true}]</ItemList>
   </body>
</html>
```

I also tried using variables instead of constants, and building the inner templates with `Papercraft.html` instead of procs, no good.

I'm on Ruby 3.1.1 and was working in Roda when I first encountered the problem, but the example output from the README.rb snip is just dropping it into an empty script and throwing a `puts` in front.

Edit: Also ran against 2.7.5 with same results.

**Comment by noteflakes** [comment]
Thanks for reporting this. Fixed in version 0.24. Please let me know if you encounter any more difficulties.
