### ISSUE TITLE
SOAP XML?

### ISSUE THREAD

**Issue by aemadrid** [digital-fabric/rubyoshka#9]
How do you deal with SOAP XML like?

```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:xsd="http://www.w3.org/2001/XMLSchema"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <PosRequest xmlns="http://Some.Site">
      <Ver1.0>
        <Header>
          <SecretAPIKey>some_secret_key</SecretAPIKey>
        </Header>
        <Transaction>
          <SomeData>
          </SomeData>
        </Transaction>
      </Ver1.0>
    </PosRequest>
  </soap:Body>
</soap:Envelope>
```

I'm curios how you generate elemtents like `<soap:Envelope`, `<soap:Body>`. or `<Ver1.0>`.

**Comment by noteflakes** [comment]
Thanks for this question. I've made some changes to facilitate most of the hassle of creating SOAP templates. It's not perfect (creating tags such as `<Ver1.0>` is still not as elegant as one would wish, but all in all it's good enough. This change is available in Papercraft 0.20, which I just released.

Here's how to express the XML above in Papercraft (note the use of double underscores, which are converted to colons):

```ruby
xml = Papercraft.xml {
  soap__Envelope(
    xmlns__soap:  'http://schemas.xmlsoap.org/soap/envelope/',
    xmlns__xsd: 'http://www.w3.org/2001/XMLSchema',
    xmlns__xsi: 'http://www.w3.org/2001/XMLSchema-instance'
  ) {
    soap__Body {
      PosRequest(xmlns: 'http://Some.Site') {
        tag('Ver1.0') {
          Header {
            SecretAPIKey 'some_secret_key'
          }
          Transaction {
            SomeData { }
          }
        }
      }
    }
  }
}
```

**Comment by aemadrid** [comment]
Very cool solution. I was thinking on the same line and had a couple of thoughts. One was maybe make the string replacement in `tag_repr` configurable. I even thought about doing `_dot_` to replace `.`. But then thought it was a bit too much. 

One problem I see with this solution is that, although I'm not aware of anybody, somebody might need to generate a tag like `<some--tag/>`. One option is to use extensions to provide something like `soap.Envelope`.

```ruby
xml = Papercraft.xml {
  soap.Envelope(
    "xmlns:soap" =>  'http://schemas.xmlsoap.org/soap/envelope/',
    "xmlns:xsd" => 'http://www.w3.org/2001/XMLSchema',
    "xmlns:xsi" => 'http://www.w3.org/2001/XMLSchema-instance'
  ) {
    soap.Body {
      PosRequest(xmlns: 'http://Some.Site') {
        tag('Ver1.0') {
          Header {
            SecretAPIKey 'some_secret_key'
          }
          Transaction {
            SomeData { }
          }
        }
      }
    }
  }
}
```

This obviously doesn't solve the issue with the attribute names but we can use string keys there. I can see that you have tag names and attributes replacement separated so we could keep the `__` to `:` there. What do you think? I still need to investigate how to implement it but have some ideas on how it could be done with `method_missing` if you think the approach is worth it.

**Comment by noteflakes** [comment]
Yeah I also thought a SOAP extension might be an interesting solution. I have very limited experience with SOAP but this may be an opportunity to implement some interesting abstractions that take the hassle out of constructing SOAP messages.

I also think it might be better to convert `__` to `:` only for symbols (for attributes at least).

If you have any ideas, sure go ahead and let me know what you came up with!

**Comment by aemadrid** [comment]
I tried playing with extensions but hitting #10 when trying to use `emit_yield` in my custom soap tags.

**Comment by aemadrid** [comment]
Added PR #11 to provide an alternative. Please check it out and let me know what you think.
